global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: '1c-server'
    static_configs:
      - targets: ['1c-server:1541']
    metrics_path: '/metrics'
    
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgresql:9187']
    
  - job_name: 'application'
    static_configs:
      - targets: ['app:8080']
      
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
